### ISSUE TITLE
Expo requires v39 rather than v38

### ISSUE THREAD

**Issue by BradKML** [Strength-Notes/StrengthNotes#22]
The App is currently not testable. Also Google Play deleted the app

**Comment by EthanJoyce** [comment]
Can you detail the exact process you go through to build it?

**Comment by BradKML** [comment]
1. Download the current version of Expo
2. Access https://expo.io/@sorbetonion/StrengthNotes
3. Uses QR code to access the mobile version
4. Error on the repo being v38 rather than v39

**Comment by EthanJoyce** [comment]
Hi,

Currently there are a large number of dependencies errors, so it will be a while until I update and publish for Expo v39. However, in the meanwhile I have uploaded an apk that should be compatible with most Android devices at this link: https://drive.google.com/file/d/1KKG4QI_XX92BXtHIJzUGHu7kFRcHIjYE/view?usp=sharing

Ethan
